{%- from tpldir ~ '/map.jinja' import mcafee with context %}

# This state assumes the pkg installer was generated by McAfee ePolicy
# Orchestrator, and so the necessary configuration is embedded in the
# installer. Also requires that the salt winrepo has been configured
# with a `mcafee` pkg definition

install-nessus-agent:
  pkg.installed:
    - name: {{ nessus.package }}
{%- if nessus.version %}
    - version: {{ nessus.version }}
{%- endif %}
    - allow_updates: True
